### ISSUE TITLE
Running the contributed command: 'extension.sideJSFlowChart' failed.

### ISSUE THREAD

**Issue by lepinekong** [kostasx/live-html-preview-v2#2]
Get error message on

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by ThomasGHenry** [comment]
Same

**Comment by kostasx** [comment]
It seems that the Flowmaker works with valid JavaScript code and produces an error when it cannot evaluate the code, e.g. when the code references external variables. 

This looks like something that needs to be fixed in the [Flowmaker](https://github.com/aryaminus/flowmaker). So I am closing this issue for now.

@lepinekong @ThomasGHenry you can check that the extension works with simple JS code, for example try to run it in a file with some simple console.log() commands. 

Feel free to re-open this issue if there's something I am missing here. Thank you both for the feedback and Happy Holidays!
